//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTTechnologies.MedScience.MVC.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MedSiteStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MedSiteStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTTechnologies.MedScience.MVC.App_LocalResources.MedSiteStrings", typeof(MedSiteStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О cайте.
        /// </summary>
        public static string AboutMenuItemAndPageTitle {
            get {
                return ResourceManager.GetString("AboutMenuItemAndPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка доступа.
        /// </summary>
        public static string AccessError {
            get {
                return ResourceManager.GetString("AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код акцивации аккаунта.
        /// </summary>
        public static string AccountActivationCode {
            get {
                return ResourceManager.GetString("AccountActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активация аккаунта.
        /// </summary>
        public static string AccountActivationTitle {
            get {
                return ResourceManager.GetString("AccountActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт с таким e-mail-ом уже существует.
        /// </summary>
        public static string AccountAlreadyExistsError {
            get {
                return ResourceManager.GetString("AccountAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт с таким e-mail-ом уже существует. Если вы забыли пароль используйте опцию &quot;Восстановление пароля&quot;.
        /// </summary>
        public static string AccountAlreadyExistsErrorWithHelp {
            get {
                return ResourceManager.GetString("AccountAlreadyExistsErrorWithHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}, {2}.
        /// </summary>
        public static string AccountNameSurnameLogin {
            get {
                return ResourceManager.GetString("AccountNameSurnameLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт успешно активирован!.
        /// </summary>
        public static string AccountSuccessfullyActivate {
            get {
                return ResourceManager.GetString("AccountSuccessfullyActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Аккаунта.
        /// </summary>
        public static string AccoutId {
            get {
                return ResourceManager.GetString("AccoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активировать аккаунт.
        /// </summary>
        public static string ActivateAccount {
            get {
                return ResourceManager.GetString("ActivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На e-mail {0} было выслано письмо с кодом активации. Если данное письмо не было получено нажмите кнопку &quot;Отправить повторно&quot;. Также проверьте папку &quot;Спам&quot;..
        /// </summary>
        public static string ActivationCodeWasSent {
            get {
                return ResourceManager.GetString("ActivationCodeWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительно.
        /// </summary>
        public static string AdditionalMenuItem {
            get {
                return ResourceManager.GetString("AdditionalMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить статью.
        /// </summary>
        public static string AddNewArticle {
            get {
                return ResourceManager.GetString("AddNewArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить автора .
        /// </summary>
        public static string AddNewAuthor {
            get {
                return ResourceManager.GetString("AddNewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить категорию.
        /// </summary>
        public static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать контейнер.
        /// </summary>
        public static string AddNewPageTile {
            get {
                return ResourceManager.GetString("AddNewPageTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить роль.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор не может менять свои роли.
        /// </summary>
        public static string AdminCannotChangeHisRoles {
            get {
                return ResourceManager.GetString("AdminCannotChangeHisRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор не может удалить свой аккаунт.
        /// </summary>
        public static string AdminCannotDeleteHimSelfError {
            get {
                return ResourceManager.GetString("AdminCannotDeleteHimSelfError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все статьи.
        /// </summary>
        public static string AllArticles {
            get {
                return ResourceManager.GetString("AllArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список статей автора {0}.
        /// </summary>
        public static string AllArticlesOfAuthor {
            get {
                return ResourceManager.GetString("AllArticlesOfAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все статьи раздела &quot;{0}&quot;.
        /// </summary>
        public static string AllArtilcesOfCategory {
            get {
                return ResourceManager.GetString("AllArtilcesOfCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все авторы.
        /// </summary>
        public static string AllAuthors {
            get {
                return ResourceManager.GetString("AllAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все авторы.
        /// </summary>
        public static string AllAuthorsTitle {
            get {
                return ResourceManager.GetString("AllAuthorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделы.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все пользователи.
        /// </summary>
        public static string AllUsersTitle {
            get {
                return ResourceManager.GetString("AllUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторы статьи.
        /// </summary>
        public static string ArticleAuthors {
            get {
                return ResourceManager.GetString("ArticleAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории статьи.
        /// </summary>
        public static string ArticleCategories {
            get {
                return ResourceManager.GetString("ArticleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст статьи.
        /// </summary>
        public static string ArticleContent {
            get {
                return ResourceManager.GetString("ArticleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание статьи.
        /// </summary>
        public static string ArticleDescription {
            get {
                return ResourceManager.GetString("ArticleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование статьи.
        /// </summary>
        public static string ArticleEditing {
            get {
                return ResourceManager.GetString("ArticleEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие.
        /// </summary>
        public static string ArticleName {
            get {
                return ResourceManager.GetString("ArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог статей.
        /// </summary>
        public static string ArticlesCatalog {
            get {
                return ResourceManager.GetString("ArticlesCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог.
        /// </summary>
        public static string ArticlesChangingLogMenuItem {
            get {
                return ResourceManager.GetString("ArticlesChangingLogMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья: {0}.
        /// </summary>
        public static string ArticleSearchName {
            get {
                return ResourceManager.GetString("ArticleSearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список статей.
        /// </summary>
        public static string ArticlesList {
            get {
                return ResourceManager.GetString("ArticlesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог изменений в статьях.
        /// </summary>
        public static string ArticlesLogGridTitle {
            get {
                return ResourceManager.GetString("ArticlesLogGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие статьи не может быть пустым.
        /// </summary>
        public static string ArticleTitleCannotBeEmptyError {
            get {
                return ResourceManager.GetString("ArticleTitleCannotBeEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статья с таким заглавием уже существует.
        /// </summary>
        public static string ArticleWithSuchNameAlreadyExistsError {
            get {
                return ResourceManager.GetString("ArticleWithSuchNameAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединенные файлы.
        /// </summary>
        public static string AttachedFiles {
            get {
                return ResourceManager.GetString("AttachedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество присоединенных файлов.
        /// </summary>
        public static string AttachedFilesCount {
            get {
                return ResourceManager.GetString("AttachedFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединить файл к статье.
        /// </summary>
        public static string AttachFileToArticle {
            get {
                return ResourceManager.GetString("AttachFileToArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время сохранения присоединенных файлов произошла ошибка.
        /// </summary>
        public static string AttachmentFilesSavingError {
            get {
                return ResourceManager.GetString("AttachmentFilesSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научная степень.
        /// </summary>
        public static string AuthorDegree {
            get {
                return ResourceManager.GetString("AuthorDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество статей автора: {0}.
        /// </summary>
        public static string AuthorHasNArticles {
            get {
                return ResourceManager.GetString("AuthorHasNArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор активирован.
        /// </summary>
        public static string AuthorIsActivated {
            get {
                return ResourceManager.GetString("AuthorIsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторы.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт автора.
        /// </summary>
        public static string AuthorsAccount {
            get {
                return ResourceManager.GetString("AuthorsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор: {0}.
        /// </summary>
        public static string AuthorSearchName {
            get {
                return ResourceManager.GetString("AuthorSearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторы.
        /// </summary>
        public static string AuthorsMenuItem {
            get {
                return ResourceManager.GetString("AuthorsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус автора подтвержден.
        /// </summary>
        public static string AuthorStatusProved {
            get {
                return ResourceManager.GetString("AuthorStatusProved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По дате создания.
        /// </summary>
        public static string ByCreationDate {
            get {
                return ResourceManager.GetString("ByCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По дате последнего изменения.
        /// </summary>
        public static string ByModificationDate {
            get {
                return ResourceManager.GetString("ByModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По наименованию.
        /// </summary>
        public static string ByName {
            get {
                return ResourceManager.GetString("ByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделы.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория с таким названием уже существует.
        /// </summary>
        public static string CategoryExistsError {
            get {
                return ResourceManager.GetString("CategoryExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество статей в разделе: {0}.
        /// </summary>
        public static string CategoryHasNArticles {
            get {
                return ResourceManager.GetString("CategoryHasNArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздел: {0}.
        /// </summary>
        public static string CategorySearchName {
            get {
                return ResourceManager.GetString("CategorySearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить информацию об авторе.
        /// </summary>
        public static string ChangeAuthorInformation {
            get {
                return ResourceManager.GetString("ChangeAuthorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время изменения.
        /// </summary>
        public static string ChangedTime {
            get {
                return ResourceManager.GetString("ChangedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить e-mail.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение адреса электронной почты пользователя.
        /// </summary>
        public static string ChangingEmailTilte {
            get {
                return ResourceManager.GetString("ChangingEmailTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма изменения пароля.
        /// </summary>
        public static string ChangingPasswordFormTitle {
            get {
                return ResourceManager.GetString("ChangingPasswordFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        public static string ChangingPasswordTitle {
            get {
                return ResourceManager.GetString("ChangingPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string ColonWithSpaceAfter {
            get {
                return ResourceManager.GetString("ColonWithSpaceAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string ContactsMenuItemAndTitle {
            get {
                return ResourceManager.GetString("ContactsMenuItemAndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержимое контейнера.
        /// </summary>
        public static string ConteinerContent {
            get {
                return ResourceManager.GetString("ConteinerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контент.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование контента (Page Content Tiles).
        /// </summary>
        public static string ContentTiles {
            get {
                return ResourceManager.GetString("ContentTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS стили контейнера /n (например: big-content-container, middle-content-container, small-content-container).
        /// </summary>
        public static string CSSStylesOfConteiner {
            get {
                return ResourceManager.GetString("CSSStylesOfConteiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные успешно сохранены.
        /// </summary>
        public static string DataIsSavedWithSuccess {
            get {
                return ResourceManager.GetString("DataIsSavedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин в DB.
        /// </summary>
        public static string DBUser {
            get {
                return ResourceManager.GetString("DBUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научная степень и другая информация о достижениях автора.
        /// </summary>
        public static string DegreeAndOtherInfo {
            get {
                return ResourceManager.GetString("DegreeAndOtherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить данный файл?.
        /// </summary>
        public static string DeleteFileConfirm {
            get {
                return ResourceManager.GetString("DeleteFileConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документы.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во публикаций.
        /// </summary>
        public static string DocumentsCount {
            get {
                return ResourceManager.GetString("DocumentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документы.
        /// </summary>
        public static string DocumentsMenuItem {
            get {
                return ResourceManager.GetString("DocumentsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string DoRegister {
            get {
                return ResourceManager.GetString("DoRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string DoSearch {
            get {
                return ResourceManager.GetString("DoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать статью.
        /// </summary>
        public static string EditArticlePageLink {
            get {
                return ResourceManager.GetString("EditArticlePageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма редактирования автора.
        /// </summary>
        public static string EditingAuthorFormTitle {
            get {
                return ResourceManager.GetString("EditingAuthorFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование информации об авторе.
        /// </summary>
        public static string EditingAuthorTitle {
            get {
                return ResourceManager.GetString("EditingAuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма изменения e-mail.
        /// </summary>
        public static string EmailChangingFormTilte {
            get {
                return ResourceManager.GetString("EmailChangingFormTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string EnterButtonName {
            get {
                return ResourceManager.GetString("EnterButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма входа.
        /// </summary>
        public static string EnterFormTitle {
            get {
                return ResourceManager.GetString("EnterFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите слово, указанное на картинке.
        /// </summary>
        public static string EnterWordToRecaptcha {
            get {
                return ResourceManager.GetString("EnterWordToRecaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ErrorPageTitle {
            get {
                return ResourceManager.GetString("ErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При сохранении данных возникли ошибки.
        /// </summary>
        public static string ErrorsFoundWhenSavingData {
            get {
                return ResourceManager.GetString("ErrorsFoundWhenSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При изменении пароля произошла ошибка!.
        /// </summary>
        public static string ErrorWhenChangingPassword {
            get {
                return ResourceManager.GetString("ErrorWhenChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данное поле должно быть заполнено.
        /// </summary>
        public static string FieldShouldBeFilled {
            get {
                return ResourceManager.GetString("FieldShouldBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы забыли пароль нажмите.
        /// </summary>
        public static string ForgetPasswordInfo {
            get {
                return ResourceManager.GetString("ForgetPasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный номер телефона (Пример: +7 351 222 22 22).
        /// </summary>
        public static string FullPhoneNumberWithExample {
            get {
                return ResourceManager.GetString("FullPhoneNumberWithExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к статье.
        /// </summary>
        public static string GoToArticle {
            get {
                return ResourceManager.GetString("GoToArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен неверный пароль.
        /// </summary>
        public static string IncorrectPasswordError {
            get {
                return ResourceManager.GetString("IncorrectPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен неверный проверочный код.
        /// </summary>
        public static string IncorrectVerificationCodeError {
            get {
                return ResourceManager.GetString("IncorrectVerificationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите фамилию или имя автора.
        /// </summary>
        public static string InputAuthorNameOrSurname {
            get {
                return ResourceManager.GetString("InputAuthorNameOrSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст указанный сверху.
        /// </summary>
        public static string InputCaptchaText {
            get {
                return ResourceManager.GetString("InputCaptchaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название раздела.
        /// </summary>
        public static string InputCategory {
            get {
                return ResourceManager.GetString("InputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата изменения.
        /// </summary>
        public static string LastChanged {
            get {
                return ResourceManager.GetString("LastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний раз заходил.
        /// </summary>
        public static string LastLogIn {
            get {
                return ResourceManager.GetString("LastLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин присоединенного аккаунта.
        /// </summary>
        public static string LinkedAccountLogin {
            get {
                return ResourceManager.GetString("LinkedAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зугрузка....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким e-mail-ом не зарегистрирован на сайте.
        /// </summary>
        public static string LoginNotFoundError {
            get {
                return ResourceManager.GetString("LoginNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход на сайт.
        /// </summary>
        public static string LogInTitle {
            get {
                return ResourceManager.GetString("LogInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string LoginWhoChanged {
            get {
                return ResourceManager.GetString("LoginWhoChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медицинские научные статьи. Здесь вы найдете информацию о здоровье, болезнях и их причинах. Статьи представляют интерес как для практикующих врачей, так и для пациентов..
        /// </summary>
        public static string MainPageDescription {
            get {
                return ResourceManager.GetString("MainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медицинские статьи, статьи о медицине, статьи о 
        ///научные статьи, медицинские статьи, статьи о медицине, статьи о здоровье, повышение квалификации.
        /// </summary>
        public static string MainPageKeyWords {
            get {
                return ResourceManager.GetString("MainPageKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string MainPageMenuItemAndTitle {
            get {
                return ResourceManager.GetString("MainPageMenuItemAndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Научные статьи по медицине (MedicineScience.ru).
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще ....
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить?.
        /// </summary>
        public static string NeedSaveQuestion {
            get {
                return ResourceManager.GetString("NeedSaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый e-mail.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to След. &gt;.
        /// </summary>
        public static string NextAbbrWithArrow {
            get {
                return ResourceManager.GetString("NextAbbrWithArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет аккаунта.
        /// </summary>
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если у вас еще нет аккаунта нажмите.
        /// </summary>
        public static string NoAccountInfo {
            get {
                return ResourceManager.GetString("NoAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено ни одной статьи.
        /// </summary>
        public static string NoArticleFound {
            get {
                return ResourceManager.GetString("NoArticleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено ни одного автора.
        /// </summary>
        public static string NoAuthorsFound {
            get {
                return ResourceManager.GetString("NoAuthorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено ни одного раздела.
        /// </summary>
        public static string NoCategoriesFound {
            get {
                return ResourceManager.GetString("NoCategoriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не являющийся администратором не может редактировать данные автора, который не привязан к его аккаунту..
        /// </summary>
        public static string NonAdminCannotManageNotLinkedAuthor {
            get {
                return ResourceManager.GetString("NonAdminCannotManageNotLinkedAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не найдено.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только Super Administrator может удалять других администраторов.
        /// </summary>
        public static string OnlySuperUserCanDeleteOtherAdminsError {
            get {
                return ResourceManager.GetString("OnlySuperUserCanDeleteOtherAdminsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядковый номер контейнера.
        /// </summary>
        public static string OrderOfConteiner {
            get {
                return ResourceManager.GetString("OrderOfConteiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип страницы.
        /// </summary>
        public static string PageType {
            get {
                return ResourceManager.GetString("PageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль успешно изменен.
        /// </summary>
        public static string PasswordIsChangedSuccessful {
            get {
                return ResourceManager.GetString("PasswordIsChangedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длинна пароля должна быть не менее {2} символов.
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На e-mail {0} было выслано письмо с кодом для изменения пароля. Если данное письмо не было получено проверьте правильность введенного вами адреса. Также проверьте папку &quot;Спам&quot;..
        /// </summary>
        public static string PasswordVerificationCodeWasSent {
            get {
                return ResourceManager.GetString("PasswordVerificationCodeWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Пред..
        /// </summary>
        public static string PreviousAbbrWithArrow {
            get {
                return ResourceManager.GetString("PreviousAbbrWithArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма редактирования профиля.
        /// </summary>
        public static string ProfileEditingFormTilte {
            get {
                return ResourceManager.GetString("ProfileEditingFormTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование профиля.
        /// </summary>
        public static string ProfileEditingTilte {
            get {
                return ResourceManager.GetString("ProfileEditingTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликована.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты быстрого поиска.
        /// </summary>
        public static string QuickSearchPanelTitle {
            get {
                return ResourceManager.GetString("QuickSearchPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по заглавию .
        /// </summary>
        public static string ReadAllArticlesDisplayNameFilterTitle {
            get {
                return ResourceManager.GetString("ReadAllArticlesDisplayNameFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенное слово и слово на картинке не совпадают.
        /// </summary>
        public static string RecaptchaError {
            get {
                return ResourceManager.GetString("RecaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата регистрации.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма регистрации.
        /// </summary>
        public static string RegistrationFormTitle {
            get {
                return ResourceManager.GetString("RegistrationFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля.
        /// </summary>
        public static string RestoaringPasswordTitle {
            get {
                return ResourceManager.GetString("RestoaringPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код восстановления пароля аккаунта.
        /// </summary>
        public static string RestorationAccountCode {
            get {
                return ResourceManager.GetString("RestorationAccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить пароль.
        /// </summary>
        public static string SavePassword {
            get {
                return ResourceManager.GetString("SavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты поиска.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать аккаунт автора.
        /// </summary>
        public static string SelectAuthorsAccount {
            get {
                return ResourceManager.GetString("SelectAuthorsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить повторно.
        /// </summary>
        public static string SendAgain {
            get {
                return ResourceManager.GetString("SendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать все результаты быстрого поиска.
        /// </summary>
        public static string ShowAllResults {
            get {
                return ResourceManager.GetString("ShowAllResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файлов и изображений на сайт.
        /// </summary>
        public static string SiteFiles {
            get {
                return ResourceManager.GetString("SiteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по сайту.
        /// </summary>
        public static string SiteSearch {
            get {
                return ResourceManager.GetString("SiteSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировать по:.
        /// </summary>
        public static string SortingBy {
            get {
                return ResourceManager.GetString("SortingBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техническая поддержка.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование контейнера.
        /// </summary>
        public static string TileEdit {
            get {
                return ResourceManager.GetString("TileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип контейнера.
        /// </summary>
        public static string TileType {
            get {
                return ResourceManager.GetString("TileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стили.
        /// </summary>
        public static string TyleStyles {
            get {
                return ResourceManager.GetString("TyleStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла неизвестная ошибка. Если данная ошибка будет повторяться, обратитесь в тех. поддержку.
        /// </summary>
        public static string UnknownErrorOccured {
            get {
                return ResourceManager.GetString("UnknownErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail пользователя.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email пользователя (Логин).
        /// </summary>
        public static string UserEmailLogin {
            get {
                return ResourceManager.GetString("UserEmailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли пользователя.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные пользователя.
        /// </summary>
        public static string UsersDataTitle {
            get {
                return ResourceManager.GetString("UsersDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string UsersMenuItem {
            get {
                return ResourceManager.GetString("UsersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь {0}.
        /// </summary>
        public static string UserWithLoginName {
            get {
                return ResourceManager.GetString("UserWithLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить данную запись?.
        /// </summary>
        public static string WantToDeleteRecordQuestion {
            get {
                return ResourceManager.GetString("WantToDeleteRecordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где отображать контент.
        /// </summary>
        public static string WhereToShowContent {
            get {
                return ResourceManager.GetString("WhereToShowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен неверный код активации. Письмо с новым кодом активации отправлено повторно..
        /// </summary>
        public static string WrongActivationCodeError {
            get {
                return ResourceManager.GetString("WrongActivationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указан не верный e-mail.
        /// </summary>
        public static string WrongEmailError {
            get {
                return ResourceManager.GetString("WrongEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное имя пользователя или пароль.
        /// </summary>
        public static string WrongLoginOrPassword {
            get {
                return ResourceManager.GetString("WrongLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и его подтверждение не совпадают.
        /// </summary>
        public static string WrongPasswordConfirmation {
            get {
                return ResourceManager.GetString("WrongPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш e-mail.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш новый пароль.
        /// </summary>
        public static string YourNewPassword {
            get {
                return ResourceManager.GetString("YourNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль.
        /// </summary>
        public static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }
    }
}
